alias ls='exa -F'
alias l='exa -F'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias b='batcat'
alias bat='batcat'
alias v='vim'
alias g='git'
alias venv='source venv/bin/activate'
alias sudo='sudo '
alias sd='peco-cd'
alias update='sudo -- sh -c "apt update && apt upgrade"'

