alias ls='exa'
alias l='exa'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias b='batcat'
alias bat='batcat'
alias v='vim'
alias g='git'
alias venv='source venv/bin/activate'
alias aslroff='sysctl -w kernel.randomize_va_space=0'
alias aslron='sysctl -w kernel.randomize_va_space=2'
alias sudo='sudo '
alias clip='win32yank.exe'
alias sd='peco-cd'
alias update='sudo -- sh -c "apt update && apt upgrade"'

